webserver:
  image: nginx
  volumes:
   - ./capstone.nginx.conf:/etc/nginx/conf.d/default.conf
   - ./workingdir/:/var/www/html/
   - ./ssl:/usr/local/etc/ssl/
  ports:
   - "80:80"
   - "443:443"